name: shpp_gardening
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Core Firebase
  firebase_core: ^3.1.1       # Stable version for your current setup
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  
  # Additional Features
  webview_flutter: ^4.13.1
  firebase_functions: ^0.0.1-dev

flutter:
  uses-material-design: true
  assets:
    - assets/



  