name: shpp_gardening
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # Core Firebase (Essential for Login & Database)
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  # Flexible versions to bypass the solving error
  functions_framework: any
  shelf: any
  webview_flutter: ^4.13.1
  firebase_functions: ^0.0.1-dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Leaf (1).png
    - assets/Mint.png
    - assets/ROSEMARY.jpg
    - assets/ORIGANUM DICTAMNUS.jpg